language: python
python:
- '3.4'
install:
- pip install devassistant
- sudo apt-get install realpath
- da pkg install dap
script:
- da twk dap pack
- da pkg lint *.dap
after_success:
- git config --global devassistant.dapi.token $DAPI_TOKEN
- da extra dap upload -d *.dap -s staging-devassistant.rhcloud.com
env:
  global:
    secure: dCacnOhnVEckP7m9Mg8+0WyxH3c7mvQjgxQlhxivBEtbxs/t5RhRzwg8Divicq49QPM0mgQPP50fdBIt3XLJrmxq4VU4SWVqKDgo1m7LMrT2fuNs6kk5fqENojf+PFHmNgL0hnXciuY7ht9Az5f1bWL+A6+/rQu4SCCw35yvGnA=
